<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Hello World</title>
    <style type="text/css">
        body {
            background-color:red;
            background-image: linear-gradient( lightseagreen,orange,yellow,gold,lawngreen,greenyellow,#dddd33, rgba(111,123,21, 0.5));
        }
        ul {
            list-style-type: square;
        }
    </style>
</head>
<body>
hey you
<ul>
    <li>
        <a href="https://www.google.com">link from template</a></li>
    <li>
        <a href="/magento-mirror/index.php">link to upper relative folder to frontend</a>
    </li>
    <li>
        <a href="/..">link to root folder</a>
    </li>
</ul>


</body>
</html>
